market/chat/urls.py
from django.urls import path
from . import views

app_name='chat'
urlpatterns = [
    path( '',views.inbox, name="inbox"), 
    path('<int:pk>/',views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_chat, name='new'),
]

market/market/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

# from core.views import index,contact


urlpatterns = [
    # path('',index, name='index'),
    path('', include('core.urls')),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('chats/',include('chat.urls')),
    # path('contact/',contact, name='contact'),
    #  path('', include(('dashboard.urls'), namespace='dashboard')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:  
#         urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

market/chat/models.py
from django.contrib.auth.models import User
from django.db import models

from item.models import Item

# Create your models here.
class Chat(models.Model):
    item = models.ForeignKey(Item, related_name='chats', on_delete=models.CASCADE)
    members= models.ManyToManyField(User,related_name='chats')
    created_at=models.DateTimeField(auto_now_add=True)
    modified_at=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('-modified_at',)

class ChatMessage(models.Model):
    chat=models.ForeignKey(Chat, related_name='messages', on_delete=models.CASCADE)
    content=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    created_by=models.ForeignKey(User, related_name='created_messages', on_delete=models.CASCADE)

market/chat/forms.py
from django import forms
from .models import ChatMessage

class ChatMessageForm(forms.ModelForm):
    class Meta:
        model=ChatMessage
        fields=('content',)
        widget={
            'content': forms.Textarea(attrs={
                'class':'w-full py-4 px-4 rounded-xl border-8 border-indigo-600'

            })
        }

market/chat/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,get_object_or_404, redirect
from item.models import Item
from .forms import ChatMessageForm
from .models import Chat
# Create your views here.
@login_required
def new_chat(request, item_pk):
    item=get_object_or_404(Item, pk=item_pk)

    if item.created_by==request.user:
        return redirect ('dashboard:index')
    
    chats= Chat.objects.filter(item=item).filter(members__in=[request.user.id])

    if chats:
        pass# return show chat page
    
    if request.method=='POST':
        form=ChatMessageForm(request.POST)

        if form.is_valid():
            chat=Chat.objects.create(item=item)
            chat.members.add(request.user)
            chat.members.add(item.created_by)
            chat.save()

            chat_message=form.save(commit=False)
            chat_message.chat=chat
            chat_message.created_by=request.user
            chat_message.save()

            return redirect('item:detail', pk=item_pk)
        
    else:
        form = ChatMessageForm()
        
    return render(request,'chat/new.html', {
        'form':form
        })

@login_required
def inbox(request):
    chats= Chat.objects.filter(members__in=[request.user.id])
    return render(request, 'chat/inbox.html',{
        'chats':chats
         })

@login_required
def detail(request,pk):
    chat= Chat.objects.filter(members__in=[request.user.id]).get(pk=pk)

    return render(request,'chat/detail.html',{
        'chat':chat})

market/chat/templates/chat/detail.html
{% extends "core/base.html" %}
{% block title %}
Chat
{% endblock title %}
{% block content %}
<h1 class="mb-6 text-3xl">Chat</h1>
    <div class="space-y-6">
        {% for message in chat.messages.all %}
            <div class="p-6 flex {% if message.created_by==request.user %}bg-blue-100 {% else %}bg-gray-100 rounded-xl 
            
            
            {% endif %} ">
                <div>
                    <p class=mb-4><strong>{{message.created_by.username}}: </strong> @{{message.created_at}}</p>
                    <p>{{message.content}} </p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

market/chat/templates/chat/inbox.html
{% extends "core/base.html" %}
{% block title %}
Inbox
{% endblock title %}
{% block content %}
<h1 class="mb-6 text-3xl">Inbox</h1>
    <div class="space-y-6">
        {% for chat in chats %}
        <a href="{% url 'chat:detail' chat.id%}">
            <div class="p-6 flex bg-gray-100 rounded-xl">
                <div class="pr-6">
                <img src="{{chat.item.image}}" class="w-20 rounded-xl">
                </div>
                <div>
                    {% for member in chat.members.all %}
                    {% if member != request.user %}
                        <p class="mb-4"><strong>{{member.username}}</strong> | {{chat.modified_at}}</p>
                        <p>{{chat.item.name}}</p>
                    {% endif %}
                    
                    {% endfor %}
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
{% endblock content %}

market/chat/templates/chat/new.html
{% extends "core/base.html" %}

{% block title %}
CHAT
{% endblock title %}
{% block content %}
<h1 class="mb-6 text-3xl">New Chat</h1>

<form method="POST" action=".">
    {% csrf_token %}

    <div class="space-y-4 border-8 border-indigo-600 ">
        {{form.as_p}}
    </div>
      
            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl" >
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
                {{form.non_field_errors}}
            </div>
        {% endif %}
            
    <button class=" mt-6 py-4 px-4 text-lg bg-teal-500 hover:bg-teal-700 rounded">SEND</button>
</form>
{% endblock content %}