market/chat/urls.py
from django.urls import path
from . import views

app_name='chat'
urlpatterns = [
    path( '',views.inbox, name="inbox"), 
    path('<int:pk>/',views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_chat, name='new'),
]

market/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name='core'

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/',views.contact, name='contact'),
    path('signup/',views.signup, name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
    # path("logout/", auth_views.LogoutView.as_view),
    
]

market/dashboard/urls.py
from django.urls import path
from . import views

app_name='dashboard'

urlpatterns=[
    path('',views.index, name='index')
]

market/item/urls.py
from django.urls import path
from . import views

app_name='item'

urlpatterns = [
    path('',views.items, name='items'),
    path('new/',views.new, name='new'),
    path('<int:pk>/', views.detail,name='detail'),
    path('<int:pk>/delete/', views.delete,name='delete'),
    path('<int:pk>/edit/', views.edit,name='edit'),
]

market/market/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

# from core.views import index,contact


urlpatterns = [
    # path('',index, name='index'),
    path('', include('core.urls')),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('chats/',include('chat.urls')),
    # path('contact/',contact, name='contact'),
    #  path('', include(('dashboard.urls'), namespace='dashboard')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:  
#         urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

market/core/models.py
from django.db import models

# Create your models here.

market/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models  import User

class SignUpForm (UserCreationForm):
    # username=forms.CharField(max_length=50, required=True)
    # email=forms.EmailField(widget=forms.EmailInput(attrs={'class':'relative'}))  
    # password1=forms.CharField( label= "Password")
    # password2=forms.CharField(label='Confirm Password')
    class Meta:
        model= User
        fields=  ('username', 'email', 'password1', 'password2')
        # Custom authentication form to add a custom field 
        username= forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Username', 
            # 'class':'px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm'
        }) )    
        email= forms.CharField(widget=forms.EmailInput(attrs={
            'placeholder': 'Your Email address', 
            'class':'px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm'
        }) )
        password1= forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'password', 
            'class':'px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm'
        }) )     
        password2= forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'confirm password', 
            'class':'px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm'
        }) )      

class LoginForm(AuthenticationForm):
    class Meta:
        model = User 
        fields = ['username','password']
        # Adding CSS classes to the login page
        username= forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Username', 
            'class':'border border-solid-slate-300 w-full px-6 py-4 rounded-xl'
        }) )
        password= forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'Enter Password', 
            'class':'w-full px-6 py-4 rounded-xl'
        }) )

market/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

from item.models import Category, Item

from .forms  import  SignUpForm
# Create your views here.
def index(request):
    items=Item.objects.filter(is_sold=False)[0:6]
    categories=Category.objects.all()
    return render(request, 'core/index.html',{
        'categories': categories,
        'items':items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method=='POST':
        form=SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form=SignUpForm ()

    return render (request,'core/signup.html',{
        'form':form
        })

# @login_required
# def logout(request):
#     logout(request)
    # messages.info(request, "Logged out successfully!")
    # return redirect("homepage")
    # return render(request, 'core/index.html')

market/core/templates/core/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title></title>
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="">
		<script src="https://cdn.tailwindcss.com" > </script>

		<title> 
        {% block title %} {% endblock %} |Market</title>
		 
	</head>
	<body>
        <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Market</a>

            <div class="space-x-6">
                <a href="{% url 'item:new' %}" class= "text-lg font-semibold hover:text-blue-500">Add Item<span class="sr-only">(current)</span></a> 
                <a href="{% url 'item:items' %}" class= "text-lg font-semibold hover:text-blue-500">Browse</a> 
                {% if request.user.is_authenticated %}
                <a href="{% url 'chat:inbox' %}" class= "px-6 py-2 text-lg font-semibold bg-green-500 text-white rounded-xl hover:text-red-700 ">Inbox</a> 
                <a href="{% url 'dashboard:index' %}" class= "px-6 py-2 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:text-blue-700 ">Dashboard</a> 
                {% comment %} <a href="{%url 'core:logout'%}" class= "px-6 py-2 text-lg font-semibold bg-red-500 text-white rounded-xl hover:text-red-700 ">Log Out</a>  {% endcomment %}


                {% else %}
                <a href="{% url 'core:signup' %}" class= "px-6 py-2 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:text-green-700 ">Sign Up</a> 
                <a href="{% url 'core:login' %}" class= "px-6 py-2 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:text-blue-700 ">Log In</a> 
                {% endif %}



            </div>
        </nav>
		<div class="px-6 py-6">
			{% comment %} <h1>The Front Page</h2>    {% endcomment %}
            
            {% block content %}
                
            {% endblock%}
                	
		</div>
		{% comment %} <script src="" async defer></script> {% endcomment %}
        <footer class="py-6 px-6 flex justify-between bg-gray-800" >
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-orange-400">About</h3>
                <p class="text-lg text-orange-500">{% lorem %}</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-brown-400">Menu</h3>
                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-yellow-500 hover:text-green-700">About</a><li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-yellow-500 hover:text-green-700">Contact</a><li>
                    <li><a href="#" class="text-lg text-yellow-500 hover:text-green-700">Privcy</a><li>
                    <li><a href="#" class="text-lg text-yellow-500 hover:text-green-700">Terms and Conditions</a><li>
                </ul>
                </ul>
            </div>
        {% comment %} </div> {% endcomment %}

        </footer>
	</body>
</html>

market/core/templates/core/contact.html
{% extends 'core/base.html' %}


{% block title %}Contact{% endblock %}
	

{% block content %}
	<h1>This is the contact page</h2>
{% endblock content %}

market/core/templates/core/index.html
{% extends 'core/base.html' %}


{% block title %}Welcome{% endblock %}
	

{% block content %}
	<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
		<h2 class="mb-12 text-2xl text-center">Newest Items</h2>

		<div class='grid grid-cols-3 gap-3'>
			
			{% for item in items %}

			<div>
				{% comment %} this url is from app item where i created a url.py file and used ph as reference id {% endcomment %}
				<a href="{%url 'item:detail' item.id  %}">
					<div class="grid min-h-[140px] w-full place-items-center overflow-x-scroll rounded-lg p-6 lg:overflow-visible">
						{% comment %} -md {% endcomment %}
						{% comment %} <img src="{{item.image.url}}" class= "object-cover object-center rounded-full h-96 w-96"> {% endcomment %}
					</div>

					<div class="p-6 bg-white  rounded-b-xl">
						<h2 class="text-2xl"> {{item.name}} </h2>
						<p class="text-gray-500">Price:{{item.price}}</p>
					</div>
				</a>
			</div>
				
			{% endfor %}
				
		</div>
	</div>

	<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
		<h2 class="mb-12 text-2xl text-center">Categories</h2>

		<div class='grid grid-cols-3 gap-3'>
		{% for category in categories %}
		<div>
			<a href="#">
				<div class="p-6 bg-white  rounded-b-xl">
					<h2 class="text-2xl"> {{category.name}} </h2>
					<p class="text-gray-500">{{category.items.count}} items</p>
				</div>
			</a>
		</div>

			
		{% endfor %}
			

		{% comment %} <div class='grid grid-cols-3 gap-3'></div> {% endcomment %}
		</div>
	</div>
{% endblock content %}
	

market/core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %}
Log In
{% endblock title %}

{% block content %}
{% comment %} <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign Up</h1>
    <form method="post" action=".">
        {% csrf_token %}
        {{form.non_field_errors}}

            <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{form.username}}
            </div>

            <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{form.email}}
            </div>

            <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>   
            {{form.password1}}
            </div>

            <div class="mb-3">
            <label class="inline-block mb-2">Repeat Password</label>
            {{form.password2}}
            </div>

            <div class="mb-12 pb-1 pt-1 text-center">
                <button
                  class="mb-3 inline-block w-full rounded px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_rgba(0,0,0,0.2)] transition duration-150 ease-in-out hover:shadow-[0_8px_9px_-4px_rgba(0,0,0,0.1),0_4px_18px_0_rgba(0,0,0,0.2)] focus:shadow-[0_8px_9px_-4px_rgba(0,0,0,0.1),0_4px_18px_0_rgba(0,0,0,0.2)] focus:outline-none focus:ring-0 active:shadow-[0_8px_9px_-4px_rgba(0,0,0,0.1),0_4px_18px_0_rgba(0,0,0,0.2)]"
                  type="button"
                  data-te-ripple-init
                  data-te-ripple-color="light"
                  style="
                    background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
                  ">
                  Sign Up
                </button>


    </form>
</div> {% endcomment %}

<div class=" w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl ">


    {% comment %} <h2 class="my-3 text-center text-3xl font-bold tracking-tight text-gray-900"> {% endcomment %}
        <h1 class="mb-6 text-3xl">Sign Up</h1>
        Log In to Your account
    </h2>


    <form  method="POST"  action="."> 
        {% csrf_token %} 


        <div class="mb-3">
            <label for="username" class="block text-sm font-medium text-gray-700 border-b-indigo-500">Username</label>
            {{form.username}}
            {% comment %} <div class="mt-1">
                <input name="username" type="username" required
                    class="px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm" />
                    
            </div> {% endcomment %}
        </div>

        <div class="mb-3">
            <label for="password" class="block text-sm font-medium text-gray-700 border-b-indigo-500">Password</label>
            {{form.password}}
            {% comment %} <div class="mt-1">
                <input name="password" type="password" autocomplete="password" required
                    class="px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm" />
                    
            </div> {% endcomment %}
        </div>

        
        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl" >
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
            </div>
        {% endif %}
            
        {{form.non_field_errors}}

        
            <button
            class="mb-3 inline-block w-full rounded px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_rgba(0,0,0,0.2)] transition duration-150 ease-in-out hover:shadow-[0_8px_9px_-4px_rgba(0,0,0,0.1),0_4px_18px_0_rgba(0,0,0,0.2)] focus:shadow-[0_8px_9px_-4px_rgba(0,0,0,0.1),0_4px_18px_0_rgba(0,0,0,0.2)] focus:outline-none focus:ring-0 active:shadow-[0_8px_9px_-4px_rgba(0,0,0,0.1),0_4px_18px_0_rgba(0,0,0,0.2)]"
        
            data-te-ripple-init
            data-te-ripple-color="light"
            style="
              background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
            ">
            LOGIN
          </button>
    
    </form>
</div>
{% endblock content %}

market/core/templates/core/signup.html
{% extends "core/base.html" %}

{% block title %}
Sign Up
{% endblock title %}

{% comment %} try bootstrap css and js from cdn if not exist in local directory {% endcomment %}
{% comment %} {% block content %}
    <div class="container">
        <h1>Sign  up</h1>
        <form action="/signup/" method="post">
            {{ form.hidden_tag() }}
            <div class="mb-3 >
                {{ form.username.label }}
                {{ form.username(class="form-control") }}
                {% if form.errors %}
                <span class="text-danger">{{ form.username.errors[0]
                    }}{% endif  %}
                </div>
                <div class="mb-3">
                    {{ form.email.label }}
                    {{ form.email(class="form-control") }}
                    {% if form.email.errors %}<span class="text-danger"> Email is already in use.</span>{% endif %}
                    {% if form.email.errors %}<span class="text-danger">Email  is already in use.</span>{% endif %}
                    {% if form.email.errors %}<span class="text-danger"> Email already exists.</span>{% endif %}
                        Please enter a valid email address.</sapn>{% endif %}}
                </div>
            <div class="row">
                <div class="col">
                    {{ form.password1.label }}<br />
                    {{ form.password1(placeholder="Password", class="form-control") }}
                    </div>
                    <div class="col">
                        {{ form.password2.label }}<br />
                        {{ form.password2(placeholder="Repeat Password", class="form-control")}}
                    </div>
                </div>

{% endblock content %} {% endcomment %}

{% comment %} {% block content %}

<div class="bg-gray-100 w-1/2 my-6 mx-auto p-6  flex  items-center justify-center px-4 sm:px-6 lg:px-8">  
    <div class="w-full max-w-md space-y-8">
        <div class="bg-white shadow-md rounded-md p-6">


            <h2 class="my-3 text-center text-3xl font-bold tracking-tight text-gray-900">
                Sign up for an account
            </h2>


            <form class="space-y-6" method="POST" action=".">
                {%csrf_token%}

                <div>
                    <label for="new-password" class="block text-sm font-medium text-gray-700">Username</label>
                    <div class="mt-1">
                        <input name="username" type="username" required
                            class="px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm" />
                            {{form.username}}
                    </div>
                </div>

                <div>
                    <label for="password" class="block text-sm font-medium text-gray-700">Email</label>
                    <div class="mt-1">
                        <input name="email" type="email-address" autocomplete="email-address" required
                            class="px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm" />
                            {{form.email}}
                    </div>
                </div>

                <div>
                    <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
                    <div class="mt-1">
                        <input name="password" type="password" autocomplete="password" required
                            class="px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm" />
                            {{form.password1}}
                    </div>
                </div>

                <div>
                    <label for="password" class="block text-sm font-medium text-gray-700">Confirm Password</label>
                    <div class="mt-1">
                        <input name="confirm_password" type="password" autocomplete="confirm-password" required
                            class="px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm" />
                            {{form.password2}}
                    </div>
                </div>

                
                {% if form.errors or form.non_field_errors %}
                    <div class="mb-3 p-6 bg-red-100 rounded-xl" >
                        {% for field in form %}
                            {{field.errors}}
                        {% endfor %}
                    </div>
                {% endif %}
                    
                {{form.non_field_errors}}

                <div>
                    <button type="submit"
                        class="flex w-full justify-center rounded-md border border-transparent bg-sky-400 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-opacity-75 focus:outline-none focus:ring-2 focus:ring-sky-400 focus:ring-offset-2">Register
                        Account
                        </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %} {% endcomment %}

{% block content %}
{% comment %} <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign Up</h1>
    <form method="post" action=".">
        {% csrf_token %}
        {{form.non_field_errors}}

            <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{form.username}}
            </div>

            <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{form.email}}
            </div>

            <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>   
            {{form.password1}}
            </div>

            <div class="mb-3">
            <label class="inline-block mb-2">Repeat Password</label>
            {{form.password2}}
            </div>

            <div class="mb-12 pb-1 pt-1 text-center">
                <button
                  class="mb-3 inline-block w-full rounded px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_rgba(0,0,0,0.2)] transition duration-150 ease-in-out hover:shadow-[0_8px_9px_-4px_rgba(0,0,0,0.1),0_4px_18px_0_rgba(0,0,0,0.2)] focus:shadow-[0_8px_9px_-4px_rgba(0,0,0,0.1),0_4px_18px_0_rgba(0,0,0,0.2)] focus:outline-none focus:ring-0 active:shadow-[0_8px_9px_-4px_rgba(0,0,0,0.1),0_4px_18px_0_rgba(0,0,0,0.2)]"
                  type="button"
                  data-te-ripple-init
                  data-te-ripple-color="light"
                  style="
                    background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
                  ">
                  Sign Up
                </button>


    </form>
</div> {% endcomment %}

<div class=" w-1/2 my-6 mx-auto lbg-white shadow-md rounded-md p-6">


    <h2 class="my-3 text-center text-3xl font-bold tracking-tight text-gray-900">
        Sign up for an account
    </h2>


    <form class="space-y-6" method="POST"  action=""> 
        {% csrf_token %} 


        <div>
            <label for="username" class="block text-sm font-medium text-gray-700 ">Username</label>
            {{form.username}}
            {% comment %} <div class="mt-1">
                <input name="username" type="username" required
                    class="px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm" />
                    
            </div> {% endcomment %}
        </div>

        <div>
            <label for="password" class="block text-sm font-medium text-gray-700 border-b-indigo-500">Email</label>
            {{form.email}}
            {% comment %} <div class="mt-1">
                <input name="email" type="email-address" autocomplete="email-address" required
                    class="px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm" />
                    
            </div> {% endcomment %}
        </div>

        <div>
            <label for="password" class="block text-sm font-medium text-gray-700 border-b-indigo-500">Password</label>
            {{form.password1}}
            {% comment %} <div class="mt-1">
                <input name="password" type="password" autocomplete="password" required
                    class="px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm" />
                    
            </div> {% endcomment %}
        </div>

        <div>
            <label for="password" class="block text-sm font-medium text-gray-700 border-b-indigo-500">Confirm Password</label>
            {{form.password2}}
            {% comment %} <div class="mt-1">
                <input name="confirm_password" type="password" autocomplete="confirm-password" required
                    class="px-2 py-3 mt-1 block w-full rounded-md border border-gray-300 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-sky-500 sm:text-sm" />
                    
            </div> {% endcomment %}
        </div>

        
        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl" >
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
                {{form.non_field_errors}}
            </div>
            
        {% endif %}
            
        

        <div>
            <button
            class="mb-3 inline-block w-full rounded px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_rgba(0,0,0,0.2)] transition duration-150 ease-in-out hover:shadow-[0_8px_9px_-4px_rgba(0,0,0,0.1),0_4px_18px_0_rgba(0,0,0,0.2)] focus:shadow-[0_8px_9px_-4px_rgba(0,0,0,0.1),0_4px_18px_0_rgba(0,0,0,0.2)] focus:outline-none focus:ring-0 active:shadow-[0_8px_9px_-4px_rgba(0,0,0,0.1),0_4px_18px_0_rgba(0,0,0,0.2)]"
        
            data-te-ripple-init
            data-te-ripple-color="light"
            style="
              background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
            ">
            Submit
          </button>
        </div>
    </form>
</div>
{% endblock content %}